// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim() ?? '';

/** Matches default Supabase JS storage namespace (`sb-<project-ref>-auth-token`). */
export function getSupabaseAuthStorageKeyPrefix(): string {
  try {
    const ref = new URL(SUPABASE_URL).hostname.split(".")[0];
    return `sb-${ref}-auth-token`;
  } catch {
    return "sb-local-auth-token";
  }
}

export function getPkceVerifierStorageKey(): string {
  return `${getSupabaseAuthStorageKeyPrefix()}-code-verifier`;
}

function supabaseUrlProjectRef(url: string): string | null {
  try {
    return new URL(url).hostname.split(".")[0] || null;
  } catch {
    return null;
  }
}

/** Decode `ref` claim from Supabase anon JWT (matches project subdomain). */
function jwtPayloadRef(token: string): string | null {
  try {
    const parts = token.split(".");
    if (parts.length < 2 || !token.startsWith("eyJ")) return null;
    let b64 = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    const pad = b64.length % 4;
    if (pad) b64 += "=".repeat(4 - pad);
    const payload = JSON.parse(atob(b64)) as { ref?: string };
    return typeof payload.ref === "string" ? payload.ref : null;
  } catch {
    return null;
  }
}

/**
 * Prefer the anon JWT whose `ref` matches `VITE_SUPABASE_URL`.
 * A mismatched anon key (wrong project) causes "Invalid API key" on Auth and REST.
 */
function selectSupabasePublicKey(url: string, anon?: string, publishable?: string): string {
  const candidates = [anon?.trim(), publishable?.trim()].filter(
    (k): k is string => Boolean(k && k.length > 0),
  );
  if (candidates.length === 0) return "";

  const hostRef = url ? supabaseUrlProjectRef(url) : null;

  if (hostRef) {
    for (const key of candidates) {
      if (!key.startsWith("eyJ")) continue;
      if (jwtPayloadRef(key) === hostRef) return key;
    }
    if (import.meta.env.DEV) {
      // eslint-disable-next-line no-console
      console.error(
        "[Supabase] No JWT matches VITE_SUPABASE_URL host.",
        "URL project:",
        hostRef,
        "anon/publishable JWT ref(s):",
        candidates.filter((k) => k.startsWith("eyJ")).map(jwtPayloadRef),
        "Set VITE_SUPABASE_ANON_KEY to the anon public key from the same project as VITE_SUPABASE_URL (Dashboard → Settings → API).",
      );
    }
  }

  const jwt = candidates.find((k) => k.startsWith("eyJ"));
  return jwt ?? candidates[0];
}

/**
 * Supabase client keys:
 * - Edge Functions + PostgREST expect `Authorization: Bearer <JWT>`.
 * - New **publishable** keys (`sb_publishable_…`) are NOT JWTs → gateway returns `401 Invalid JWT`
 *   and the browser may show "Failed to send a request to the Edge Function".
 * - Use the **anon public** JWT (`eyJ…`) from Dashboard → Settings → API as `VITE_SUPABASE_ANON_KEY`.
 */
const ANON_JWT = (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)?.trim();
const PUBLISHABLE = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined)?.trim();

const SUPABASE_KEY = selectSupabasePublicKey(SUPABASE_URL, ANON_JWT, PUBLISHABLE);

if (import.meta.env.DEV && SUPABASE_KEY.startsWith('sb_publishable_')) {
  // eslint-disable-next-line no-console
  console.error(
    '[Supabase] Publishable key alone breaks Edge Functions. Set VITE_SUPABASE_ANON_KEY to the JWT anon key (Dashboard → Settings → API → anon public, starts with eyJ).',
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Implicit flow: tokens arrive in the URL hash after redirects. Works when users open email
    // confirmation links on a different device than signup (PKCE requires the same browser where
    // sign-up ran). OAuth + magic links use the same detection path.
    detectSessionInUrl: true,
    flowType: 'implicit',
  }
});
