// AUTO-GENERATED by scripts/harvest-flight-routes.ts — do not edit by hand.
// Every route below returned real, bookable offers from the Duffel API when
// harvested. Volatile data (prices, availability) is intentionally NOT stored.
// Regenerate with: bunx tsx scripts/harvest-flight-routes.ts

export interface FlightRouteCatalogEntry {
  /** Stable URL segment for /flights/{slug} */
  slug: string;
  /** Slug of the reverse direction (may or may not exist in this catalog). */
  reverseSlug: string;
  origin: string;
  originCode: string;
  destination: string;
  destinationCode: string;
  /** Carriers observed on this route in Duffel results. */
  airlines: string[];
  /** Whether Duffel returned round-trip offers for this route. */
  roundTripAvailable: boolean;
  /** Fastest observed one-way duration, in minutes. */
  minDurationMinutes?: number;
}

export const FLIGHT_ROUTES_VALIDATED_AT = "2026-08-31";

export const flightRouteCatalog: FlightRouteCatalogEntry[] = [
  {
    "origin": "Chicago",
    "originCode": "ORD",
    "destination": "Miami",
    "destinationCode": "MIA",
    "slug": "chicago-to-miami",
    "reverseSlug": "miami-to-chicago",
    "airlines": [
      "Alaska Airlines",
      "American Airlines"
    ],
    "minDurationMinutes": 188,
    "roundTripAvailable": false
  },
  {
    "origin": "Los Angeles",
    "originCode": "LAX",
    "destination": "New York",
    "destinationCode": "JFK",
    "slug": "los-angeles-to-new-york",
    "reverseSlug": "new-york-to-los-angeles",
    "airlines": [
      "Alaska Airlines",
      "American Airlines"
    ],
    "minDurationMinutes": 323,
    "roundTripAvailable": false
  },
  {
    "origin": "New York",
    "originCode": "JFK",
    "destination": "Los Angeles",
    "destinationCode": "LAX",
    "slug": "new-york-to-los-angeles",
    "reverseSlug": "los-angeles-to-new-york",
    "airlines": [
      "Alaska Airlines",
      "American Airlines",
      "Sun Country"
    ],
    "minDurationMinutes": 361,
    "roundTripAvailable": false
  }
];

const bySlug = new Map(flightRouteCatalog.map((r) => [r.slug, r]));

export function getFlightRoute(slug?: string): FlightRouteCatalogEntry | undefined {
  return slug ? bySlug.get(slug) : undefined;
}

/** Routes sharing an origin or destination with the given route. */
export function relatedFlightRoutes(
  route: FlightRouteCatalogEntry,
  limit = 6,
): FlightRouteCatalogEntry[] {
  const reverse = bySlug.get(route.reverseSlug);
  const others = flightRouteCatalog.filter(
    (r) =>
      r.slug !== route.slug &&
      r.slug !== route.reverseSlug &&
      (r.originCode === route.originCode ||
        r.destinationCode === route.destinationCode ||
        r.destinationCode === route.originCode),
  );
  return [...(reverse ? [reverse] : []), ...others].slice(0, limit);
}

/** All indexable city-pair paths. Round-trip variants are not routed. */
export function indexableFlightRoutePaths(): string[] {
  return flightRouteCatalog.map((r) => `/flights/${r.slug}`);
}
